services:
  postgres:
    image: postgres:16-alpine
    container_name: volunteerhub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: volottdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d volottdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
